import requests
from langchain_core.tools import tool



@tool
def sandbox_code_tool(code: str, requirements: list[str] = [], language: str = "python") -> str:
    """
    Runs LLM-generated Python or Node.js code inside an isolated Docker sandbox.

    Parameters:
    - code: The source code generated by the language model to execute.
    - requirements: A list of dependencies to install via pip (Python) or npm (Node.js).
    - language: Either 'python' or 'node'.

    Returns:
    - A string combining stdout and stderr from the execution result.
    """
    print("running code")
    response = requests.post("http://localhost:8000/run", json={
        "code": code,
        "requirements": requirements,
        "language": language
    })
    out = response.json()
    print(out)
    return f"STDOUT:\n{out['stdout']}\nSTDERR:\n{out['stderr']}"